package kv

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetEntryHandlerFunc turns a function with the right signature into a get entry handler
type GetEntryHandlerFunc func(GetEntryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEntryHandlerFunc) Handle(params GetEntryParams) middleware.Responder {
	return fn(params)
}

// GetEntryHandler interface for that can handle valid get entry params
type GetEntryHandler interface {
	Handle(GetEntryParams) middleware.Responder
}

// NewGetEntry creates a new http.Handler for the get entry operation
func NewGetEntry(ctx *middleware.Context, handler GetEntryHandler) *GetEntry {
	return &GetEntry{Context: ctx, Handler: handler}
}

/*GetEntry swagger:route GET /kv/{key} kv getEntry

GetEntry get entry API

*/
type GetEntry struct {
	Context *middleware.Context
	Handler GetEntryHandler
}

func (o *GetEntry) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetEntryParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
